# Generated by Django 2.2 on 2020-07-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_productgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygame',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productgame',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
